language: node_js
node_js:
  - "8.5"

services:
  - mongodb

before_script:
  - sleep 5

script:
  - npm run-script test-travis

after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"